mail_address: user@gmail.com
infile: /shared/home/croux/scratch/myProject/mySequences.fas
region: coding
nspecies: 2
nameA: NAMEA
nameB: NAMEB
nameOutgroup: NA
config_yaml: /shared/home/croux/scratch/myProject/example_config_2pop.yaml
timeStamp: anyRandomName
population_growth: constant
modeBarrier: bimodal
max_N_tolerated: 0.2
Lmin: 100
nMin: 6
mu: 0.00000002763
rho_over_theta: 0.5
N_min: 1000
N_max: 500000
Tsplit_min: 10000
Tsplit_max: 1750000
M_min: 1
M_max: 40

